config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :categories 
  root "contacts#index"
  post "/hallo" => "contacts#hallo"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :contact
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorizations, dependent: :destroy
  has_many :contacts, through: :categorizations, source: :contact
end

app/models/contact.rb
class Contact < ApplicationRecord
   has_many :categorizations, dependent: :destroy
   has_many :categories, through: :categorizations




  def self.search_contacts(search)
    where("number ILIKE ? OR body ILIKE ?", "%#{search}", "%#{search}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def create
    category = Category.new(strong_params)
    category.save
    redirect_to '/contacts'
  end
  private
  def strong_params
    params.require(:category).permit(:title)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @category = Category.new
    @categories = Category.all
    account_sid = 'AC288a3fafasf'
    auth_token = '027ae70ee04caasfas7e6'
    @client = Twilio::REST::Client.new account_sid, auth_token
       messages = @client.messages
      #  @mymessage = messages.where(body: params[:search])

    @contact = Contact.new
    if params[:search].present?
      @contacts = Contact.search_contacts(params[:search])
    else
      @contacts = Contact.all
  end

  end
  def hallo
    # @categories = Category.all

    if Category.exists?(title: params[:Body])
      @category = Category.find_by_title!(params[:Body])
      contact = Contact.create(number: params[:From], body: params[:Body] )
      categorization =  Categorization.create(category_id: @category.id, contact_id: contact.id)
    end
  end

  def new
    twiml = Twilio::TwiML::Response.new do |r|
        r.Message "The Robots are coming! Head for the hills!"
    end
  end
  def create
    # account_sid = 'AC288a35e4a1b5650264a87bb04cf8da32'
    # auth_token = '027ae70ee04caaf04a2e335ed9c737e6'
    # @client = Twilio::REST::Client.new account_sid, auth_token
    #
    # @client.messages.list.each do |message|
    #    if message.direction == "inbound"
    #       Contact.create(number: message.from, body: message.body)
    #     end
    # end
    # redirect_to root_path
  end
  def update
  end
  def show
  end


  private
  def strong_params

  end
  def find_category
    Category.all.each do |cat|
      cat.include?(params[:body])
      @category = cat
    end
  end

  def authentication
    account_sid = 'AC288a35e4a1b5650264a87bb04cf8da32'
    auth_token = '027ae70ee04caaf04a2e335ed9c737e6'
    @client = Twilio::REST::Client.new account_sid, auth_token
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/index.html.erb
  <%= form_tag contacts_path, method: :get, class: 'something' do %>
    <div class="input-group add-on">
      <%= text_field_tag :search, "", class: 'form-control'  %>
      <div class="input-group-btn">

        <%= button_tag(type: 'submit', class: "btn btn-default") do %>
         <span class="icon-envelope"></span> Search
        <% end %>
      </div>
    </div>
  <% end %>

<%= form_for @category do |f| %>
  <%= f.text_field :title %>
  <%= f.submit %>
  <% end %>
  -------------------------  <br>
  <% @categories.each do |cat| %>
    <%= cat.title %> <br>
<% end %>
  ---------------------
  <br>
<% @contacts.each do |contact| %>
  <%= contact.number %>
  <br>
  <%= contact.body %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>